app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
	// Authentification
    Route::auth();	
	// Sondage
	Route::get('/', ['as' => 'home', 'uses' => 'PollController@index']);
	Route::resource('poll', 'PollController');
    // Vote
    Route::get('vote/{id}', 'VoteController@create');
	Route::post('vote/{id}', 'VoteController@store');
});

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{

	/**
	 * La table utilisée par le modèle
	 *
	 * @var string
	 */
	protected $table = 'answers';

	/**
	 * On utilise les dates de mise à jour
	 *
	 * @var bool
	 */
	public $timestamps = true;

	/**
	 * Colonnes pour l'assignement de masse
	 *
	 * @var array
	 */
	protected $fillable = ['answer'];

	/**
	 * Relation de type 1:n
	 *
	 * @return Illuminate\Database\Eloquent\Relations
	 */
	public function poll()
	{
		return $this->belongsTo('App\Models\Poll');
	}

}

app/Models/Poll.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Poll extends Model
{

	/**
	 * La table utilisée par le modèle
	 *
	 * @var string
	 */
	protected $table = 'polls';

	/**
	 * On utilise les dates de mise à jour
	 *
	 * @var bool
	 */
	public $timestamps = true;

	/**
	 * Attributs autorisés en ensignement de masse.
	 *
	 * @var array
	 */
	protected $fillable = ['question'];

	/**
	 * Relation de type 1:n
	 *
	 * @return Illuminate\Database\Eloquent\Relations
	 */
	public function answers()
	{
		return $this->hasMany('App\Models\Answer');
	}

	/**
	 * Relation de type n:n
	 *
	 * @return Illuminate\Database\Eloquent\Relations
	 */
	public function users()
	{
		return $this->belongsToMany('App\Models\User')->withTimestamps();
	}

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	/**
	 * Relation de type 1:n
	 *
	 * @return Illuminate\Database\Eloquent\Relations
	 */
	public function polls()
	{
		return $this->belongsToMany('App\Models\Poll')->withTimestamps();
	}

	/**
	 * Vérification rôle administrateur
	 *
	 * @return bool
	 */
	public function isAdmin()
	{
		return $this->admin == 1;
	}

	/**
	 * Test de déjà voté
	 *
	 * @param  integer $id
	 * @return bool
	 */
	public function hasVoted($id)
	{
		return $this->polls->contains($id);
	}

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PollController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\PollRepository;
use App\Http\Requests\PollUpdateRequest;
use App\Http\Requests\PollCreateRequest;

class PollController extends Controller
{


	/**
	 * Instance de PollRepository
	 *
	 * @var App\Repositories\PollRepository
	 */
	protected $pollRepository;

	/**
	 * Crée une nouvelle instance de PollController
	 *
	 * @param App\Repositories\PollRepository $pollRepository
	 * @return void
	 */
	public function __construct(PollRepository $pollRepository)
	{
		// Les middlewares
		$this->middleware('admin', ['except' => ['index', 'show']]);
		$this->middleware('ajax', ['only' => ['store', 'update']]);

		$this->pollRepository = $pollRepository;
	}

	/**
	 * Traitement de l'URL de base, affichage des sondages
	 *
	 * @return View
	 */
	public function index()
	{
		return view('index', $this->pollRepository->getPaginate(4));
	}

	/**
	 * Affichage du formulaire de création
	 *
	 * @return View
	 */
	public function create()
	{
		return view('polls.create');
	}

	/**
	 * Traitement du formulaire de création
	 *
	 * @param  App\Http\Requests\PollCreateRequest $request;
	 * @return Redirect
	 */
	public function store(PollCreateRequest $request)
	{
		$this->pollRepository->store($request);

		return response()->json();
	}

	/**
	 * Affichage d'un sondage
	 *
	 * @param  integer $id
	 * @return View
	 */
	public function show($id)
	{
		return view('polls.resultats', $this->pollRepository->getPollWithAnswersAndDone($id));
	}

	/**
	 * Affichage du formulaire de modification d'un sondage
	 *
	 * @param  integer $id
	 * @return Mixed
	 */
	public function edit($id)
	{
		// On vérifie que le sondage n'a pas déjà reçu un vote
		if($this->pollRepository->checkPoll($id))
		{
			return redirect('/');
		}

		$poll = $this->pollRepository->getPollWithAnswers($id);

		return view('polls.edit', $poll);
	}

	/**
	 * Traitement du formulaire de modification
	 *
	 * @param  App\Http\Requests\PollUpdateRequest $request;
	 * @param  integer $id
	 * @return Redirect
	 */
	public function update(PollUpdateRequest $request, $id)
	{
		$this->pollRepository->update($request, $id);

		return response()->json();
	}

	/**
	 * Traitement de la suppression d'un sondage
	 *
	 * @param  integer $id
	 * @return Redirect
	 */
	public function destroy($id)
	{
		$this->pollRepository->destroy($id);
		
		return redirect('/');
	}

}

app/Http/Controllers/VoteController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\PollRepository;
use Illuminate\Http\Request;

class VoteController extends Controller
{

	/**
	 * Instance de PollRepository
	 *
	 * @var Lib\Gestion\PollRepository
	 */
	protected $pollRepository;

	/**
	 * Crée une nouvelle instance de VoteController
	 *
	 * @param App\Repositories\PollRepository $pollRepository
	 * @return void
	 */
	public function __construct(PollRepository $pollRepository)
	{
		$this->middleware('voted');

		$this->pollRepository = $pollRepository;
	}

	/**
	 * Affichage du formulaire de vote
	 *
	 * @return View
	 */
	public function create($id)
	{
		return view('polls.sondage', $this->pollRepository->getPollWithAnswers($id));
	}	

	/**
	 * Traitement du formulaire de vote
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  integer $id
	 * @return Redirect
	 */
	public function store(Request $request, $id)
	{	
		$this->pollRepository->saveVote($id, $request->input('options'), $request->user());

		return redirect(route('poll.show', [$id]))->with('info', 'Merci d\'avoir participé à ce sondage !');
	}	

}

resources/views/index.blade.php
@extends('template')

@section('contenu')
  <br>
	<div class="col-sm-offset-3 col-sm-6">

		<!-- Affichage des alertes -->	
		@if(session()->has('info'))
			<div class="alert alert-success">{{ session('info') }}</div>
		@endif

		<div class="panel panel-primary">

			<div class="panel-heading">
				<h3 class="panel-title">Liste des sondages</h3>
			</div>

			<table class="table">

					<!-- Balayage de tous les sondages -->		
					@foreach ($polls as $poll)
						<tr>
							<td class="text-primary"><strong>{{ $poll->question }}</strong></td>
							<td>
								{!! link_to_route('poll.show', 'Voir', [$poll->id], ['class' => 'btn btn-success btn-block']) !!}
							</td>
							@if(auth()->check() && auth()->user()->admin)
								<td>
									{!! link_to_route('poll.edit', 'Modifier', [$poll->id], ['class' => 'btn btn-warning btn-block' . (in_array($poll->question, $polls_voted)? ' disabled' : '')]) !!}
								</td>
								<td>
									{!! Form::open(['method' => 'DELETE', 'route' => ['poll.destroy', $poll->id]]) !!}
										{!! Form::submit('Supprimer', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Voulez-vous vraiment supprimer ce sondage ?\')']) !!}
									{!! Form::close() !!}
								</td>
							@endif
						</tr>
					@endforeach
					<!-- Fin du balayage -->

			</table>

		</div>
		@if(auth()->check() && auth()->user()->admin)
			{!! link_to_route('poll.create', 'Ajouter un sondage', null, ['class' => 'btn btn-info pull-right']) !!}
		@endif

		<!-- Pagination -->
		{!! $polls->render(); !!}
		
	</div>
@stop

resources/views/polls/create.blade.php
@extends('polls/template_form')

@section('form')
					{!! Form::open(['route' => 'poll.store', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}	
						<p><strong>Question</strong></p>
						<div class="form-group">
							{!! Form::text('question', null, ['class' => 'form-control', 'placeholder' => 'Question']) !!}
							<small class="help-block"></small>
						</div><hr>
						<div id="answers">
					  		<p><strong>Réponses</strong></p>
							@for($i = 0; $i < 3; $i++)
								<div class="row ligne">
									<div class="form-group">
										<div class="col-md-10">
											{!! Form::text('answers[]', null, ['class' => 'form-control']) !!}
											<small class="help-block"></small>
										</div>
										<div class="col-md-2">
											<button type="button" class="btn btn-danger">Supprimer</button>
										</div>
									</div>
								</div>						
							@endfor
						</div><hr>
						<div class="row">
	  						<button id="add_answer" type="button" class="btn btn-primary pull-right">Ajouter une réponse</button>
	  					</div><hr>
	  					<div class="form-group">
							{!! Form::submit('Envoyer', ['class' => 'btn btn-primary pull-right']) !!}
						</div>
					{!! Form::close() !!}
@stop

resources/views/polls/edit.blade.php
@extends('polls/template_form')

@section('form')
					{!! Form::open(['route' => ['poll.update',  $poll->id], 'method' => 'put', 'class' => 'form-horizontal panel']) !!}
						<p><strong>Question</strong></p>
						<div class="form-group">
					  		{!! Form::text('question', $poll->question, ['class' => 'form-control', 'placeholder' => 'Question']) !!}
							<small class="help-block"></small>
						</div><hr>
						<div id="answers">
							<p><strong>Réponses</strong></p>
							@foreach ($poll->answers as $i => $answer)
								<div class="row ligne">
									<div class="form-group">
										<div class="col-md-10">
											{!! Form::text('answers[]', $answer->answer, ['class' => 'form-control']) !!}
											<small class="help-block"></small>
										</div>
										<div class="col-md-2">
											<button type="button" class="btn btn-danger">Supprimer</button>
										</div>
									</div>
								</div>						
							@endforeach
						</div><hr>
						<div class="form-group">
							<button id="add_answer" type="button" class="btn btn-primary pull-right">Ajouter une réponse</button>
						</div><hr>
						<div class="form-group">
							{!! Form::submit('Envoyer', ['class' => 'btn btn-primary pull-right']) !!}
						</div>
					{!! Form::close() !!}
@stop

resources/views/polls/resultats.blade.php
@extends('template')

@section('contenu')
  <br>
	<div class="col-sm-offset-3 col-sm-6">

		<!-- Informations en alertes -->
		@if(auth()->guest())
			<div class="alert alert-warning">Vous devez être connecté pour participer aux sondages !</div>
		@elseif($done)
			@if(session('info'))
				<div class="alert alert-success">{{ session('info') }}</div>
			@else
				<div class="alert alert-warning">Vous avez déjà participé à ce sondage !</div>
			@endif
		@endif

		<div class="panel panel-primary">
			<div class="panel-heading">
				{{ $poll->question }} 
				@if(auth()->check() && !$done)
					{!! link_to('vote/' . $poll->id, 'Votez vous aussi !', ['class' => 'btn btn-info btn-xs pull-right']) !!}
				@endif
			</div>
			<div class="panel-body"> 
				<p>Voici les résultats actuels :</p>

					<!-- Balayage de toutes les réponses -->
					@foreach ($poll->answers as $index => $answer)
						<p>
							<strong>{{ $answer->answer }}</strong> : {{ $answer->result }}
							@if ($answer->result > 1) votes	@else vote	@endif
						</p>
						<div class="progress">
							<?php $pourcentage = $total == 0 ? 0 : number_format($answer->result / $total * 100) ?>
						  <div class="progress-bar progress-bar-success" style="width: {{ $pourcentage }}%;">
						  	{{ $pourcentage }} %
						  </div>
						</div> 	
					@endforeach
					<!-- Fin du balayage -->

			</div>	
		</div>

		@if(!session('info'))
			<a href="javascript:history.back()" class="btn btn-primary">
				<span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
			</a>
		@else
			{!! link_to('/', 'Retour à l\'accueil', ['class' => 'btn btn-primary']) !!}		
		@endif
		
	</div>
@stop

resources/views/polls/sondage.blade.php
@extends('template')

@section('contenu')
	<br>
	<div class="col-sm-offset-3 col-sm-6">
		<div class="panel panel-primary">
			<div class="panel-heading">{{ $poll->question }}</div>
			<div class="panel-body"> 

				<!-- Formulaire de vote -->
				{!! Form::open(['url' => 'vote/' . $poll->id]) !!}
					@foreach ($poll->answers as $index => $answer)
						<div class="radio">
							<label>
								{!! Form::radio('options', $answer->id, $index === 0) !!} {{ $answer->answer }}
							</label>
						</div>
					@endforeach
					{!! Form::submit('Envoyer !', ['class' => 'btn btn-info pull-right']) !!}
				{!! Form::close() !!}
				<!-- Fin du formulaire -->

			</div>
		</div>
	</div>
@stop

resources/views/polls/template_form.blade.php
@extends('template')

@section('contenu')
	<div class="col-sm-offset-2 col-sm-8">
		<br>
		<div class="panel panel-primary">	
			<div class="panel-heading">Création d'un sondage</div>
			<div class="panel-body"> 
				<div class="col-sm-12">

					<!-- Formulaire -->
					@yield('form')
					<!-- Fin du formulaire -->

				</div>
			</div>
		</div>
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
		</a>
	</div>
@stop		

@section('scripts')
	{!! Html::script('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js') !!}
	<script>

		$(function(){		

			// Nombre de réponses au départ
			var answer_number = $('#answers .ligne').length;

			// Suppression d'une ligne de réponse (utilisation de "on" pour gérer les boutons créés dynamiquement)
			$(document).on('click', '.btn-danger', function(){
				if($('#answers .ligne').length > 3)	$(this).parents('.ligne').remove();	
			});

			// Ajout d'une ligne de réponse
			$("#add_answer").click(function() {
				var html = '<div class="row ligne">\n<div class="form-group">\n'
				+ '<div class="col-md-10">\n'
				+ '{!! Form::text('answers[]', null, ['class' => 'form-control']) !!}\n'
				+ '<small class="help-block"></small>\n'
				+ '</div>\n<div class="col-md-2">\n<button type="button" class="btn btn-danger">Supprimer</button>\n</div>\n</div>\n';
				++answer_number;
				$('#answers').append(html);	
			});

			// Soumission 
			$(document).on('submit', 'form', function(e) {  
				e.preventDefault();
				$.ajax({
					method: $(this).attr('method'),
					url: $(this).attr('action'),
					data: $(this).serialize(),
					dataType: "json"
				})
				.done(function(data) {
					window.location.href = '{!! url('/') !!}';
				})
				.fail(function(data) {
					var obj = data.responseJSON;
					// Nettoyage préliminaire					
					for(var i = 0; i < answer_number + 1; ++i) {
						$('.help-block').eq(i).text('');
						$('.form-group').eq(i).removeClass('has-error');						
					} 
					// Balayage de l'objet
					$.each(data.responseJSON, function (key, value) {
						// Traitement des erreurs de la question
						if(key == 'question') {
							$('.help-block').eq(0).text(value);
							$('.form-group').eq(0).addClass('has-error');							
						}
						// Traitement des erreurs des réponses
						else {
							var i = parseInt(key.slice(-1)) + 1;
							var texte = value[0].replace(key, 'réponse');
							$('.help-block').eq(i).text(texte);
							$('.form-group').eq(i).addClass('has-error');							
						}
					});
				});
			});

		})

	</script>
@stop			
 

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mon joli site</title>
    {!! Html::style('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css') !!}
    {!! Html::style('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css') !!}
    <!--[if lt IE 9]>
      {!! Html::style('https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js') !!}
      {!! Html::style('https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js') !!}
    <![endif]-->
  </head>
  <body>
    <header class="jumbotron">
      <div class="container">
        <h1  class="page-header">{!! link_to('/', 'Le site des sondages !') !!}</h1>
        @if(auth()->check())
          <div class="btn-group pull-right">          
            {!! link_to('logout', 'Deconnexion', ['class' => 'btn btn-info']) !!}
          </div>
        @else
          {!! link_to('login', 'Se connecter', ['class' => 'btn btn-info pull-right']) !!}
        @endif
      </div>
    </header>
    <div class="container">
      @yield('contenu')
    </div>
    @yield('scripts')
  </body>
</html>